name: bookapp_customer
description: "A Flutter app for browsing, booking, and managing various services with ease."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.9.0
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  pinput: ^5.0.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_html: ^3.0.0
  carousel_slider: ^5.1.1
  table_calendar: ^3.2.0


  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # State Management
  get: ^4.7.2
  provider: ^6.1.5


  # Networking
  http: ^1.5.0
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.5
  webview_flutter: ^4.13.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^14.0.2
  logger: ^2.6.1


  # File & Image Picker
  image_picker: ^1.1.2

  # Payment Services
  flutter_stripe: ^11.5.0
  razorpay_flutter: ^1.4.0


  # notification services

  flutter_local_notifications: ^19.4.0
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  permission_handler: ^12.0.1
  app_settings: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/pgw/


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter/Inter_18pt-Medium.ttf
        - asset: assets/fonts/Inter/Inter_18pt-SemiBold.ttf
        - asset: assets/fonts/Inter/Inter_18pt-Bold.ttf
        - asset: assets/fonts/Inter/Inter_24pt-SemiBold.ttf

