// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo1ryZ8Fhf6m2rtyD1p2vq3Kn41vyU5hY',
    appId: '1:33593358051:web:e2f0757e20990bdbea77d6',
    messagingSenderId: '33593358051',
    projectId: 'bookappnotification-cdca2',
    authDomain: 'bookappnotification-cdca2.firebaseapp.com',
    storageBucket: 'bookappnotification-cdca2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ-9pRpMMSAJIQvrVNOIuYRMNW--aPMtU',
    appId: '1:33593358051:android:35354bf9b7ccd3cdea77d6',
    messagingSenderId: '33593358051',
    projectId: 'bookappnotification-cdca2',
    storageBucket: 'bookappnotification-cdca2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYqMJaf46tdb2jN67D9ItnREpyP6hecxc',
    appId: '1:33593358051:ios:913063e8799db64fea77d6',
    messagingSenderId: '33593358051',
    projectId: 'bookappnotification-cdca2',
    storageBucket: 'bookappnotification-cdca2.firebasestorage.app',
    iosBundleId: 'com.example.bookappCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYqMJaf46tdb2jN67D9ItnREpyP6hecxc',
    appId: '1:33593358051:ios:913063e8799db64fea77d6',
    messagingSenderId: '33593358051',
    projectId: 'bookappnotification-cdca2',
    storageBucket: 'bookappnotification-cdca2.firebasestorage.app',
    iosBundleId: 'com.example.bookappCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo1ryZ8Fhf6m2rtyD1p2vq3Kn41vyU5hY',
    appId: '1:33593358051:web:98899237784d0f7fea77d6',
    messagingSenderId: '33593358051',
    projectId: 'bookappnotification-cdca2',
    authDomain: 'bookappnotification-cdca2.firebaseapp.com',
    storageBucket: 'bookappnotification-cdca2.firebasestorage.app',
  );
}
