const Map<String, String> ArabicTr = {
  "Appointment not available": "الموعد غير متاح",
  "Please contact support": "يرجى الاتصال بالدعم",
  "The rating field is required for product review":
      "حقل التقييم مطلوب لمراجعة المنتج",
  "You have not booking anything yet": "لم تقم بحجز أي شيء بعد",
  "You have not bought this service yet!": "لم تقم بشراء هذه الخدمة بعد!",
  "Product added into the cart": "تمت إضافة المنتج إلى سلة التسوق",
  "Product removed successfully!": "تمت إزالة المنتج بنجاح!",
  "Cart updated successfully!": "تم تحديث العربة بنجاح!",
  "Calendar event not created": "لم يتم إنشاء حدث التقويم",
  "A contact request was sent successfully": "تم إرسال طلب الاتصال بنجاح",
  "Content not available. Please try another language.":
      "المحتوى غير متوفر. يرجى تجربة لغة أخرى.",
  "You have not bought this product yet!": "لم تقم بشراء هذا المنتج بعد!",
  "Your review submitted successfully": "تم إرسال المراجعة الخاصة بك بنجاح",
  "Coupon is not valid!": "القسيمة غير صالحة!",
  "Sorry, coupon has expired!": "عذرا، انتهت صلاحية القسيمة!",
  "Your cart is empty!": "سلة التسوق الخاصة بك فارغة!",
  "Sorry, product out of stock!": "عذرا، المنتج غير متوفر!",
  "You already added this event into your wishlist!":
      "لقد قمت بالفعل بإضافة هذا الحدث إلى قائمة أمنياتك!",
  "Added to your wishlist successfully": "تمت الإضافة إلى قائمة أمنياتك بنجاح",
  "Removed From wishlist successfully": "تمت الإزالة من قائمة الرغبات بنجاح",
  "Your profile has been updated successfully":
      "لقد تم تحديث ملفك الشخصي بنجاح",
  "Something went wrong!": "لقد حدث خطأ ما!",
  "Password updated successfully": "تم تحديث كلمة المرور بنجاح",
  "new_password_confirmation": "تأكيد كلمة المرور الجديدة",
  "new_password": "كلمة المرور الجديدة",
  "first_name": "الاسم الأول",
  "password_confirmation": "تأكيد كلمة المرور",
  "password": "كلمة المرور",
  "username": "اسم المستخدم",
  "message": "رسالة",
  "subject": "موضوع",
  "email": "بريد إلكتروني",
  "address": "عنوان",
  "phone": "هاتف",
  "gateway": "بوابة",
  "name": "اسم",
  "Incorrect username or password": "اسم المستخدم أو كلمة المرور غير صحيحة",
  "Sorry, your account has been deactivated": "عذرًا، لقد تم تعطيل حسابك",
  "Please verify your email address": "يرجى التحقق من عنوان بريدك الإلكتروني",
  "Captcha error! try again later or contact site admin.":
      "خطأ في الكابتشا! حاول مرة أخرى لاحقًا أو اتصل بمسؤول الموقع.",
  "Please verify that you are not a robot.": "يرجى التأكد من أنك لست روبوتًا.",
  "Search by location": "البحث حسب الموقع",
  "Search by name": "البحث حسب الاسم",
  "Field is missing!": "الحقل مفقود!",
  "404": "404",
  "Service Inquiry": "الاستعلام عن الخدمة",
  "NO BLOG FOUND": "لم يتم العثور على مدونة",
  "Contact for service inquiry": "الاتصال للاستفسار عن الخدمة",
  "We regret to inform you that the service you are trying to book is currently unavailable. Please contact our support team for further assistance":
      "يؤسفنا إبلاغك بأن الخدمة التي تحاول حجزها غير متوفرة حاليًا.",
  "View All Vendors": "عرض جميع البائعين",
  "Google Calendar": "تقويم جوجل",
  "Wait for the payment confirmation mail": "انتظر رسالة تأكيد الدفع",
  "Meeting Url": "رابط الاجتماع",
  "Your have booked this service successfully": "لقد قمت بحجز هذه الخدمة بنجاح",
  "Congratulations": "تهانينا",
  "Available Time Slots": "الفترات الزمنية المتاحة",
  "Search by Order Number/Product Name": "البحث حسب رقم الطلب/اسم المنتج",
  "Back to Home": "العودة إلى المنزل",
  "Appointment Time": "وقت التعيين",
  "NO TESTIMONIAL FOUND": "لم يتم العثور على شهادة",
  "NO CATEGORIES FOUND": "لم يتم العثور على فئات",
  "Choose Your Staff": "اختر موظفيك",
  "Meeting Passcode": "رمز مرور الاجتماع",
  "Service": "خدمة",
  "Paid Via": "المدفوعة عن طريق",
  "Duration": "مدة",
  "Booking No.": "رقم الحجز",
  "Close": "يغلق",
  "Saturday": "السبت",
  "pending": "قيد الانتظار",
  "accepted": "مقبول",
  "Orders Details": "تفاصيل الطلبات",
  "rejected": "مرفوض",
  "Download Invoice": "تحميل الفاتورة",
  "Staff Name": "اسم الموظفين",
  "Service Address": "عنوان الخدمة",
  "Booking Status": "حالة الحجز",
  "Booking details": "تفاصيل الحجز",
  "NO STAFF FOUND": "لم يتم العثور على أي موظفين",
  "NO SERVICE FOUND": "لم يتم العثور على الخدمة",
  "NO VENDOR FOUND": "لم يتم العثور على بائع",
  "View All Vendor": "عرض الكل البائع",
  "Most Affordable Package": "الحزمة الأكثر بأسعار معقولة",
  "Share on": "شارك على",
  "CONTINUE READING": "مواصلة القراءة",
  "No Service Available": "لا توجد خدمة متاحة",
  "Or Login With": "أو تسجيل الدخول باستخدام",
  "Free": "حر",
  "NO WISHLISTS FOUND": "لم يتم العثور على قوائم الرغبات",
  "Service Features": "مميزات الخدمة",
  "Friday": "جمعة",
  "Thursday": "يوم الخميس",
  "Wednesday": "الأربعاء",
  "Tuesday": "يوم الثلاثاء",
  "Monday": "الاثنين",
  "Sunday": "الأحد",
  "Add Review": "أضف مراجعة",
  "Save Changes": "حفظ التغييرات",
  "Total Appointments": "إجمالي التعيينات",
  "Total Product Orders": "إجمالي طلبات المنتجات",
  "Total Wishlists": "إجمالي قوائم الرغبات",
  "NO ORDER FOUND": "لم يتم العثور على أي طلب",
  "NO APPOINTMENTS FOUND": "لم يتم العثور على مواعيد",
  "Postcode/Zip": "الرمز البريدي/الرمز البريدي",
  "to": "ل",
  "Procced as guest checkout": "تمت معالجتها كخروج ضيف",
  "No Time Slot Found": "لم يتم العثور على فتحة زمنية",
  "Next Step": "الخطوة التالية",
  "Prev Step": "الخطوة السابقة",
  "Search by name/location": "البحث بالاسم/الموقع",
  "Select Staff": "حدد طاقم العمل",
  "Online": "متصل",
  "Gold": "ذهب",
  "Sliver": "قطعة من الجبن",
  "Recommended": "مُستَحسَن",
  "Extend": "يمتد",
  "Purchase": "شراء",
  "year": "سنة",
  "month": "شهر",
  "lifetime": "حياة",
  "Lifetime": "حياة",
  "Yearly": "سنوي",
  "Monthly": "شهريا",
  "review": "مراجعة",
  "star of": "نجم",
  "reviews": "مراجعات",
  "Offline": "غير متصل",
  "Orders completed": "اكتملت الطلبات",
  "Services Available": "الخدمات المتاحة",
  "Service Type": "نوع الخدمة",
  "Staffs": "الموظفين",
  "Image/Service": "الصورة/الخدمة",
  "Do you want to book this service": "هل تريد حجز هذه الخدمة",
  "Related Services": "الخدمات ذات الصلة",
  "Related Service": "الخدمة ذات الصلة",
  "1 Stars": "1 نجوم",
  "2 Stars": "2 نجوم",
  "3 Stars": "3 نجوم",
  "4 Stars": "4 نجوم",
  "5 Stars": "5 نجوم",
  "This service has no review yet": "هذه الخدمة ليس لديها مراجعة حتى الآن",
  "Services Found": "تم العثور على الخدمات",
  "images": "الصور",
  "Please note that you can upload a maximum of":
      "يرجى ملاحظة أنه يمكنك تحميل الحد الأقصى",
  "Show All": "إظهار الكل",
  "Enter Service Title": "أدخل عنوان الخدمة",
  "a": "أ",
  "Service Title": "عنوان الخدمة",
  "Service Found": "تم العثور على الخدمة",
  "Enter Password": "أدخل كلمة المرور",
  "Already a member": "بالفعل عضوا",
  "Login Now": "تسجيل الدخول الآن",
  "Confirmation": "تأكيد",
  "Payment": "قسط",
  "Information": "معلومة",
  "Date & Time": "التاريخ والوقت",
  "Staff": "طاقم عمل",
  "Services": "خدمات",
  "Visit Store": "قم بزيارة المتجر",
  "Search By Location": "البحث حسب الموقع",
  "Search Service": "خدمة البحث",
  "Person": "شخص",
  "Appointment Date": "تاريخ التعيين",
  "Service Name": "اسم الخدمة",
  "Appointment details": "تفاصيل الموعد",
  "Appointments": "المواعيد",
  "Service Available": "الخدمة متاحة",
  "Booking Time": "وقت الحجز",
  "Booking Date": "تاريخ الحجز",
  "Maximum": "الحد الأقصى",
  "Minimum": "الحد الأدنى",
  "Service Details": "تفاصيل الخدمة",
  "Verified User": "مستخدم تم التحقق منه",
  "Total Service": "الخدمة الشاملة",
  "All Services": "جميع الخدمات",
  "Zoom Meeting": "اجتماع التكبير",
  "Find Or Choose Your Staff": "ابحث عن موظفيك أو اخترهم",
  "Please Select a Date for Available Schedule":
      "الرجاء تحديد تاريخ للجدول الزمني المتاح",
  "Select Date & Time": "حدد التاريخ والوقت",
  "Make Payment": "إجراء الدفع",
  "Select Payment Method": "حدد طريقة الدفع",
  "Your Nearest Location": "أقرب موقعك",
  "Booking Service Available": "خدمة الحجز متاحة",
  "Service Description": "وصف الخدمة",
  "Book Now": "احجز الآن",
  "Our Address": "عنواننا",
  "Service Provider": "مزود الخدمة",
  "Business Days": "أيام العمل",
  "All Reviews": "جميع التقييمات",
  "Total Reviews": "إجمالي المراجعات",
  "Print": "مطبعة",
  "Delivered": "تم التوصيل",
  "On delivery": "عند التسليم",
  "On review": "قيد المراجعة",
  "Order placed": "تم تقديم الطلب",
  "Unit Price": "سعر الوحدة",
  "Find Anything From Nearest Location To Make A Booking":
      "ابحث عن أي شيء من أقرب موقع لإجراء الحجز",
  "Star": "نجم",
  "Ticket": "تذكرة",
  "Paid Amount": "المبلغ المدفوع",
  "Shipping Cost": "تكلفة الشحن",
  "Login with Google": "تسجيل الدخول مع جوجل",
  "Login with Facebook": "تسجيل الدخول مع الفيسبوك",
  "Authorize.net": "Authorize.net",
  "Vendor name/username": "اسم البائع/اسم المستخدم",
  "No Post Found": "لم يتم العثور على مشاركة",
  "All Posts": "جميع المشاركات",
  "Search Posts": "البحث في المشاركات",
  "Posts": "دعامات",
  "Method": "طريقة",
  "star": "نجم",
  "Message sent successfully": "تم إرسال الرسالة بنجاح",
  "Sign up successfully completed.Please Login Now":
      "تم التسجيل بنجاح. الرجاء تسجيل الدخول الآن",
  "A verification mail has been sent to your email address":
      "تم إرسال بريد التحقق إلى عنوان البريد الإلكتروني الخاص بك",
  "A mail has been sent to your email address":
      "تم إرسال بريد إلى عنوان بريدك الإلكتروني",
  "Sorry, you are offline": "عذرا، أنت غير متصل",
  "Super Admin": "المشرف الفائق",
  "404 not found": "404 غير موجود",
  "No Faq Found": "لم يتم العثور على الأسئلة الشائعة",
  "only .zip file is allowed.": "يُسمح فقط بملف ‎.zip.",
  "Max upload size is 20 MB": "الحد الأقصى لحجم التحميل هو 20 ميغابايت",
  "Specifications": "تحديد",
  "Contact Vendor": "اتصل بالمورد",
  "Vendor": "بائع",
  "Cart Total": "إجمالي العربة",
  "Linkedin": "ينكدين",
  "Twitter": "تغريد",
  "Facebook": "فيسبوك",
  "Price : Low to High": "السعر: من الأقل إلى الأعلى",
  "Price : High to Low": "السعر: من الأعلى إلى الأقل",
  "Date : Oldest on top": "التاريخ : الأقدم في الأعلى",
  "Date : Newest on top": "التاريخ : الأحدث في الأعلى",
  "Search by Title": "البحث حسب العنوان",
  "Vendor username": "اسم مستخدم البائع",
  "Found": "وجد",
  "Only .zip file is allowed.": "يُسمح فقط بملف ‎.zip.",
  "Product Details": "تفاصيل المنتج",
  "Filter": "فلتر",
  "Find Now": "ابحث الآن",
  "Customer": "عميل",
  "Vendor Details": "تفاصيل البائع",
  "Read Less": "اقرأ أقل",
  "Read More": "اقرأ المزيد",
  "Show Less": "عرض أقل",
  "Zip Code": "الرمز البريدي",
  "All Blog Post": "كل منشور المدونة",
  "Comments": "تعليقات",
  "This product has no review yet": "هذا المنتج ليس لديه مراجعة بعد",
  "Visit Profile": "زيارة الملف الشخصي",
  "Vendor Profile Available": "ملف تعريف البائع متاح",
  "Contact Now": "اتصل الآن",
  "Enter vendor name": "أدخل اسم البائع",
  "Enter location": "أدخل الموقع",
  "Vendors": "الباعة",
  "Max upload size 5 MB": "الحد الأقصى لحجم التحميل 5 ميجابايت",
  "Reply": "رد",
  "No Message Found": "لم يتم العثور على رسالة",
  "Replies": "الردود",
  "Support Ticket Details": "تفاصيل تذكرة الدعم",
  "Closed": "مغلق",
  "Open": "يفتح",
  "Pending": "قيد الانتظار",
  "Enter Subject": "أدخل الموضوع",
  "Create a Support Ticket": "إنشاء تذكرة دعم",
  "Ticket ID": "معرف التذكرة",
  "Status": "حالة",
  "Submit a Ticket": "إرسال تذكرة",
  "Go Back": "عُد",
  "Download": "تحميل",
  "Ordered Product": "المنتج المطلوب",
  "Paid amount": "المبلغ المدفوع",
  "Payment Information": "معلومات الدفع",
  "Billing Address": "عنوان الفواتير",
  "Shipping Address": "عنوان الشحن",
  "print": "مطبعة",
  "Order Date": "تاريخ الطلب",
  "Order": "طلب",
  "My order details": "تفاصيل طلبي",
  "Order Details": "تفاصيل الطلب",
  "completed": "مكتمل",
  "processing": "يعالج",
  "Order Number": "رقم الطلب",
  "Payment Status": "حالة الدفع",
  "Order Status": "حالة الطلب",
  "Orders": "طلبات",
  "Dashboard": "لوحة القيادة",
  "Support Tickets": "تذاكر الدعم",
  "My Orders": "طلباتي",
  "Thank you": "شكرًا لك",
  "We have sent you a mail with an invoice":
      "لقد أرسلنا لك بريدًا يحتوي على فاتورة",
  "Your transaction was successful": "كانت معاملتك ناجحة",
  "usually within 24–48 hours": "عادة في غضون 24-48 ساعة",
  "We answer every request as quickly as we can":
      "نحن نجيب على كل طلب بأسرع ما يمكن",
  "Your transaction request was received and sent for review":
      "تم استلام طلب المعاملة الخاص بك وإرساله للمراجعة",
  "Success": "نجاح",
  "Razorpay": "رازورباي",
  "PayPal": "باي بال",
  "Instamojo": "إنستاموجو",
  "Paystack": "الراتب",
  "Flutterwave": "موجة الرفرفة",
  "MercadoPago": "ميركادو باجو",
  "Mollie": "مولي",
  "Paytm": "بايتم",
  "Stripe": "شريط",
  "Citibank": "سيتي بنك",
  "Bank of America": "بنك أوف أمريكا",
  "Shipping Method": "طريقة الشحن",
  "Enter Product Name": "أدخل اسم المنتج",
  "Product Name": "اسم المنتج",
  "Cart": "عربة",
  "Shop": "محل",
  "Enter Location": "أدخل الموقع",
  "About Us": "معلومات عنا",
  "Login": "تسجيل الدخول",
  "Signup": "اشتراك",
  "Logout": "تسجيل الخروج",
  "Home": "بيت",
  "Blog": "مدونة",
  "Blogs": "مدونات",
  "FAQ": "التعليمات",
  "Contact": "اتصال",
  "I’m Looking for": "أبحث عن",
  "Sort By": "فرز حسب",
  "Price": "سعر",
  "Search": "يبحث",
  "View": "منظر",
  "More Details": "مزيد من التفاصيل",
  "Subscribe to Our Newsletter": "اشترك في النشرة الإخبارية لدينا",
  "Enter Your Email Address": "أدخل عنوان بريدك الإلكتروني",
  "Subscribe": "يشترك",
  "Follow Us": "تابعنا",
  "Useful Links": "روابط مفيدة",
  "No Link Found": "لم يتم العثور على رابط",
  "Contact Us": "اتصل بنا",
  "No Work Process Found": "لم يتم العثور على عملية عمل",
  "No Feature Found": "لم يتم العثور على أي ميزة",
  "No Information Found": "لم يتم العثور على معلومات",
  "Categories": "فئات",
  "All": "الجميع",
  "Filter Price": "سعر التصفية",
  "off": "عن",
  "Description": "وصف",
  "Features": "سمات",
  "Reviews": "التعليقات",
  "Comment": "تعليق",
  "Rating": "تصنيف",
  "Submit": "يُقدِّم",
  "Click Here": "انقر هنا",
  "Enter Full Name": "أدخل الاسم الكامل",
  "Enter Contact Number": "أدخل رقم الاتصال",
  "Enter Email": "أدخل البريد الإلكتروني",
  "Category": "فئة",
  "Email Address": "عنوان البريد الإلكتروني",
  "Password": "كلمة المرور",
  "Lost your password": "فقدت كلمة المرور الخاصة بك",
  "First Name": "الاسم الأول",
  "Last Name": "اسم العائلة",
  "Phone Number": "رقم التليفون",
  "Address": "عنوان",
  "City": "مدينة",
  "State": "ولاية",
  "Country": "دولة",
  "Search Blog": "بحث في المدونة",
  "Search By Title": "البحث حسب العنوان",
  "Share": "يشارك",
  "Tweet": "سقسقة",
  "Enter Your Full Name": "أدخل اسمك الكامل",
  "Enter Your Email": "أدخل بريدك الإلكتروني",
  "Enter Email Subject": "أدخل موضوع البريد الإلكتروني",
  "Write Your Message": "اكتب رسالتك",
  "Send": "يرسل",
  "Username": "اسم المستخدم",
  "Confirm Password": "تأكيد كلمة المرور",
  "Proceed": "يتابع",
  "Reset Password": "إعادة تعيين كلمة المرور",
  "New Password": "كلمة المرور الجديدة",
  "Confirm New Password": "تأكيد كلمة المرور الجديدة",
  "Edit Profile": "تحرير الملف الشخصي",
  "Change Password": "تغيير كلمة المرور",
  "Product Orders": "طلبات المنتجات",
  "Account Information": "معلومات الحساب",
  "Name": "اسم",
  "Email": "بريد إلكتروني",
  "Phone": "هاتف",
  "Edit Your Profile": "تحرير ملف التعريف الخاص بك",
  "Contact Number": "رقم الاتصال",
  "Current Password": "كلمة المرور الحالية",
  "Date": "تاريخ",
  "Details": "تفاصيل",
  "Location": "موقع",
  "No Partner Found": "لم يتم العثور على شريك",
  "About Company": "عن الشركة",
  "More Features": "المزيد من الميزات",
  "Search By Category": "البحث حسب الفئة",
  "Items": "أغراض",
  "Item": "غرض",
  "Enter Shop Location": "أدخل موقع المتجر",
  "About": "عن",
  "Read more": "اقرأ المزيد",
  "View Profile": "عرض الملف الشخصي",
  "Overview Of": "نظرة عامة على",
  "Member since": "عضو منذ",
  "Show More": "عرض المزيد",
  "Subject": "موضوع",
  "By Admin": "بواسطة المشرف",
  "By": "بواسطة",
  "Admin": "مسؤل",
  "Explore Popular Categories": "اكتشف الفئات الشائعة",
  "All Categories": "جميع الفئات",
  "Save to Wishlist": "حفظ في قائمة الرغبات",
  "Saved": "أنقذ",
  "View All": "عرض الكل",
  "View Details": "عرض التفاصيل",
  "View More": "عرض المزيد",
  "Subscribe Us": "اشترك معنا",
  "Enter email": "أدخل البريد الإلكتروني",
  "Stay update with us and get offer": "ابق على اطلاع معنا واحصل على العرض",
  "Pricing": "التسعير",
  "Reset All": "إعادة ضبط الكل",
  "Available": "متاح",
  "Default": "تقصير",
  "Newest": "الأحدث",
  "Oldest": "الأقدم",
  "High to Low": "من الأعلى إلى الأدنى",
  "Low to High": "منخفض إلى مرتفع",
  "Recent Posts": "المشاركات الأخيرة",
  "Forgot password": "هل نسيت كلمة السر",
  "Don't have an account": "ليس لديك حساب",
  "to Signup": "للتسجيل",
  "Already have an account": "لديك حساب بالفعل",
  "to Login": "لتسجيل الدخول",
  "User": "مستخدم",
  "Wishlists": "قوائم الرغبات",
  "Serial": "مسلسل",
  "Action": "فعل",
  "Remove": "يزيل",
  "Update Profile": "تحديث الملف الشخصي",
  "Forget Password": "نسيت كلمة المرور",
  "Send me a recovery link": "أرسل لي رابط الاسترداد",
  "My Wishlist": "قائمة أمنياتي",
  "Wishlist": "قائمة الرغبات",
  "Year": "سنة",
  "More From": "المزيد من",
  "Message": "رسالة",
  "Send message": "أرسل رسالة",
  "Share Now": "شارك الآن",
  "Products": "منتجات",
  "1 star and higher": "1 نجمة وما فوق",
  "2 stars and higher": "2 نجوم وما فوق",
  "3 stars and higher": "3 نجوم فما فوق",
  "4 stars and higher": "4 نجوم فما فوق",
  "5 stars": "5 نجوم",
  "Available Now": "متوفر الآن",
  "Cart is Empty": "سلة التسوق فارغة",
  "Product": "منتج",
  "Quantity": "كمية",
  "Stock": "مخزون",
  "Total": "المجموع",
  "Avilable Now": "متاح الآن",
  "In Stock": "في الأوراق المالية",
  "Out Of Stock": "إنتهى من المخزن",
  "Total Quantity": "الكمية الإجمالية",
  "Total Price": "السعر الإجمالي",
  "Update Cart": "تحديث العربة",
  "Checkout": "الدفع",
  "Billing Details": "تفاصيل الفواتير",
  "Ship to a different address": "الشحن إلى عنوان مختلف",
  "Shipping Details": "تفاصيل الشحن",
  "Method Name": "اسم الطريقة",
  "Charge": "تكلفة",
  "Order Summary": "ملخص الطلب",
  "Subtotal": "المجموع الفرعي",
  "Shipping Charge": "رسوم الشحن",
  "Payment Method": "طريقة الدفع",
  "Choose a Payment Method": "اختر طريقة الدفع",
  "Card Number": "رقم البطاقة",
  "CVC Number": "رقم التحقق من البطاقة (CVC).",
  "Expiry Month": "شهر انتهاء الصلاحية",
  "Expiry Year": "سنة انتهاء الصلاحية",
  "Instructions": "تعليمات",
  "Attachment": "مرفق",
  "Place Order": "وضع النظام",
  "Enter Coupon Code": "أدخل رمز القسيمة",
  "Apply": "يتقدم",
  "Add to Cart": "أضف إلى السلة",
  "Order Now": "اطلب الآن",
  "Related Product": "المنتجات ذات الصلة",
  "Ratings": "التقييمات",
  "Tax": "ضريبة",
  "Discount": "تخفيض",
  "The page you are looking for might have been moved, renamed, or might never existed.":
      "ربما تم نقل الصفحة التي تبحث عنها، أو أعيدت تسميتها، أو ربما لم تكن موجودة على الإطلاق.",
  "Language": "اللغة",
  "Send OTP": "إرسال رمز التحقق",
  "Sending…": "جاري الإرسال…",
  "Please enter the account that you want to reset the password":
      "يرجى إدخال الحساب الذي تريد إعادة تعيين كلمة المرور له",
  "Error": "خطأ",
  "Passwords do not match": "كلمتا المرور غير متطابقتين",
  "Signup failed": "فشل التسجيل",
  "Settings": "الإعدادات",
  "Enter OTP": "أدخل رمز التحقق",
  "Resend OTP": "إعادة إرسال رمز التحقق",
  "A 6 Digit OTP has been sent to your email address":
      "تم إرسال رمز تحقق مكون من 6 أرقام إلى بريدك الإلكتروني",
  "Please enter a new password for your account!":
      "يرجى إدخال كلمة مرور جديدة لحسابك!",
  "Hello, Welcome to BookApp": "مرحبًا، أهلاً بك في BookApp",
  "Popular Services": "الخدمات الشعبية",
  "Customer Account": "حساب العميل",
  "Account": "الحساب",
  "Notifications": "الإشعارات",
  "App Notifications": "إشعارات التطبيق",
  "Arabic": "العربية",
  "language changed to": "تم تغيير اللغة إلى",
  "No matches found": "لم يتم العثور على نتائج",
  "Confirm Logout?": "تأكيد تسجيل الخروج؟",
  "Are you sure you want to logout?": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
  "Summary": "الملخص",
  "Missing reset credentials": "بيانات إعادة التعيين مفقودة",
  "Create a new password for your account.": "أنشئ كلمة مرور جديدة لحسابك.",
  "Input minimum 6 characters": "أدخل 6 أحرف على الأقل",
  "Please select a date and a time slot!": "يرجى اختيار تاريخ ووقت!",
  "Please select number of persons!": "يرجى اختيار عدد الأشخاص!",
  "Previous": "السابق",
  "Next": "التالي",
  "Pick a date to see available time slots.":
      "اختر تاريخًا لعرض الأوقات المتاحة.",
  "Number of Persons": "عدد الأشخاص",
  "No slots available for this date.": "لا توجد أوقات متاحة لهذا التاريخ.",
  "Full Name": "الاسم الكامل",
  "Please enter your phone number": "يرجى إدخال رقم هاتفك",
  "Please enter your address": "يرجى إدخال عنوانك",
  "Payable Amount": "المبلغ المستحق",
  "Payment process is cancelled.": "تم إلغاء عملية الدفع.",
  "Payment Failed": "فشل الدفع",
  "Your payment is successful": "تم الدفع بنجاح",
  "Google Pay": "جوجل باي",
  "MidTrans": "ميدترانس",
  "Service is Booked": "تم حجز الخدمة",
  "Booking ID": "معرّف الحجز",
  "Service Booking": "حجز الخدمة",
  "Mark All as Read": "تحديد الكل كمقروء",
  "Marked all as read": "تم تحديد الكل كمقروء",
};
